-- ============================================================
-- STOKI — Database Schema v1
-- Run this in Supabase SQL Editor (Dashboard → SQL Editor → New query)
-- ============================================================

-- Enable UUID generation
create extension if not exists "pgcrypto";

-- ============================================================
-- STORES
-- Top-level tenant. All other data scoped to store_id.
-- ============================================================
create table if not exists stores (
  id          uuid primary key default gen_random_uuid(),
  owner_id    uuid not null references auth.users(id) on delete cascade,
  name        text not null,
  phone       text,
  plan        text not null default 'free' check (plan in ('free', 'starter', 'growth')),
  timezone    text not null default 'Africa/Johannesburg',
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  deleted_at  timestamptz
);

-- ============================================================
-- PRODUCTS
-- Core inventory entity.
-- ============================================================
create table if not exists products (
  id            uuid primary key default gen_random_uuid(),
  store_id      uuid not null references stores(id) on delete cascade,
  name          text not null,
  price         numeric(10,2) not null default 0,
  cost          numeric(10,2) not null default 0,
  qty           integer not null default 0,
  reorder_point integer not null default 5,
  sku           text,
  photo_url     text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  deleted_at    timestamptz
);

-- ============================================================
-- SALES
-- Immutable record. Price captured at time of sale.
-- ============================================================
create table if not exists sales (
  id             uuid primary key default gen_random_uuid(),
  store_id       uuid not null references stores(id) on delete cascade,
  product_id     uuid references products(id) on delete set null,
  qty            integer not null default 1,
  price_at_sale  numeric(10,2) not null,
  channel        text not null default 'app' check (channel in ('app', 'whatsapp', 'ussd')),
  recorded_at    timestamptz not null default now(),
  created_at     timestamptz not null default now()
);

-- ============================================================
-- RESTOCKS
-- Tracks inventory additions and cost basis.
-- ============================================================
create table if not exists restocks (
  id          uuid primary key default gen_random_uuid(),
  store_id    uuid not null references stores(id) on delete cascade,
  product_id  uuid references products(id) on delete set null,
  qty_added   integer not null,
  cost        numeric(10,2),
  supplier_id uuid,
  created_at  timestamptz not null default now()
);

-- ============================================================
-- DEBTORS
-- Credit book entity.
-- ============================================================
create table if not exists debtors (
  id               uuid primary key default gen_random_uuid(),
  store_id         uuid not null references stores(id) on delete cascade,
  name             text not null,
  phone            text,
  total_owed       numeric(10,2) not null default 0,
  last_reminded_at timestamptz,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  deleted_at       timestamptz
);

-- ============================================================
-- CREDIT ENTRIES
-- Individual credit transactions.
-- ============================================================
create table if not exists credit_entries (
  id          uuid primary key default gen_random_uuid(),
  store_id    uuid not null references stores(id) on delete cascade,
  debtor_id   uuid not null references debtors(id) on delete cascade,
  amount      numeric(10,2) not null,
  items_json  jsonb,
  settled_at  timestamptz,
  created_at  timestamptz not null default now()
);

-- ============================================================
-- ALERTS
-- Generated by rules engine and AI layer.
-- ============================================================
create table if not exists alerts (
  id              uuid primary key default gen_random_uuid(),
  store_id        uuid not null references stores(id) on delete cascade,
  type            text not null check (type in ('out_of_stock', 'low_stock', 'ai_insight', 'debtor', 'weekly_report')),
  message         text not null,
  read_at         timestamptz,
  action_taken_at timestamptz,
  created_at      timestamptz not null default now()
);

-- ============================================================
-- UPDATED_AT TRIGGER
-- Auto-update updated_at on row changes
-- ============================================================
create or replace function set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger stores_updated_at
  before update on stores
  for each row execute function set_updated_at();

create trigger products_updated_at
  before update on products
  for each row execute function set_updated_at();

create trigger debtors_updated_at
  before update on debtors
  for each row execute function set_updated_at();

-- ============================================================
-- ROW LEVEL SECURITY
-- Store data is never cross-accessible between owners.
-- ============================================================
alter table stores         enable row level security;
alter table products       enable row level security;
alter table sales          enable row level security;
alter table restocks       enable row level security;
alter table debtors        enable row level security;
alter table credit_entries enable row level security;
alter table alerts         enable row level security;

-- Helper: get current user's store id
create or replace function my_store_id()
returns uuid as $$
  select id from stores where owner_id = auth.uid() and deleted_at is null limit 1;
$$ language sql stable security definer;

-- STORES: owner can read/write their own store
create policy "owner_stores" on stores
  for all using (owner_id = auth.uid());

-- PRODUCTS
create policy "owner_products" on products
  for all using (store_id = my_store_id());

-- SALES
create policy "owner_sales" on sales
  for all using (store_id = my_store_id());

-- RESTOCKS
create policy "owner_restocks" on restocks
  for all using (store_id = my_store_id());

-- DEBTORS
create policy "owner_debtors" on debtors
  for all using (store_id = my_store_id());

-- CREDIT ENTRIES
create policy "owner_credit_entries" on credit_entries
  for all using (store_id = my_store_id());

-- ALERTS
create policy "owner_alerts" on alerts
  for all using (store_id = my_store_id());

-- ============================================================
-- ATOMIC INCREMENT FUNCTIONS (used by repositories)
-- Avoids race conditions on qty/total_owed updates.
-- ============================================================
create or replace function increment_product_qty(
  p_store_id uuid,
  p_product_id uuid,
  p_delta integer
) returns void as $$
begin
  update products
  set qty = qty + p_delta
  where id = p_product_id and store_id = p_store_id;
end;
$$ language plpgsql security definer;

create or replace function increment_debtor_owed(
  p_store_id uuid,
  p_debtor_id uuid,
  p_delta numeric
) returns void as $$
begin
  update debtors
  set total_owed = total_owed + p_delta
  where id = p_debtor_id and store_id = p_store_id;
end;
$$ language plpgsql security definer;

-- ============================================================
-- INDEXES
-- ============================================================
create index if not exists products_store_id_idx    on products(store_id) where deleted_at is null;
create index if not exists sales_store_id_idx       on sales(store_id);
create index if not exists sales_recorded_at_idx    on sales(store_id, recorded_at desc);
create index if not exists debtors_store_id_idx     on debtors(store_id) where deleted_at is null;
create index if not exists alerts_store_id_idx      on alerts(store_id, created_at desc);
create index if not exists credit_entries_debtor_idx on credit_entries(debtor_id);
